= Критерії оцінки лабораторних робіт

При оцінюванні лабораторної роботи береться до уваги наступні аспекти:

- Виконання завдань
- Дотримання термінів
- Знання теоретичної частини
- Засвоєння матеріалу

== Виконання завдань

Лабораторна робота оцінюється за наступними критеріями:

- Правильність та ефективність обраного алгоритму.
- Дотримання правил нотації при побудові блок-схеми.
- Читабельність та правильне оформлення блок-схеми.
- Реалізація алгоритму в обраній мові програмування.
- Відповідність реалізації програми блок-схемі.
- Загальне оформлення роботи.

== Дотримання термінів

Лабораторна робота вважається зданою вчасно, якщо у студентському репозиторії фінальний коміт зроблено до закінчення відведеного часу для відповідної лабораторної роботи.

== Знання теоретичної частини

Теоретична частина містить тестові запитання по темі лабораторної роботи та завдання на реалізацію блок-схеми. Блок-схема надсилається окремо у вкладенні, електронним листом до викладача для перевірки. Блок-схеми, надіслані пізніше ніж за 5 хвилин до завершення часу, відведеного на виконання теоретичної частини, не приймаються до перевірки.

== Засвоєння матеріалу

Перевірка засвоєння матеріалу відбувається у форматі діалогу з викладачем, під час якого обговорюються попередні роботи студента (репозиторій, теоретична робота), сфери застосування алгоритмів, альтернативні алгоритми та інше.