name: Publish to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Antora and the Antora Lunr Extension
        run: npm install antora @antora/lunr-extension

      - name: Install Kroks
        run: npm install asciidoctor-kroki

      - name: Generate Site
        run: npx antora site.yaml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment

      - name: Log deployment URL
        run: echo "Deployed to ${{ steps.deployment.outputs.page_url }}"